### ISSUE TITLE
How to set respone_timeout?

### ISSUE THREAD

**Issue by wyfSunflower** [LarsJK/ObjectiveLibModbus#1]
I want to set a connect timeout,such as obj.response_timeout=5,when obj can not connect successful in 5 seconds, I want to call disconnect method,now I can not access the response_timeout property which was enclosured in struct.please tell me how to do,thanks!

**Comment by LarsJK** [comment]
Hi,
This project is no longer supported and this feature is not implemented.. Ib recommend forking the project and implementing yourself.. Should be fairly easy:

http://libmodbus.org/docs/v3.1.4/modbus_set_error_recovery.html
http://libmodbus.org/docs/v3.1.4/modbus_set_response_timeout.html
